Suse
tactycal/agent pull request #5
Opened 2017-04-26 06:43 UTC by lobiCode

Add support for `openSUSE` and `SLES`.

2017-05-05 07:57 UTC, dominikznidar requested changes

2017-05-05 07:57 UTC, dominikznidar commented on Makefile
> +RPM 	      := sles opensuse
Please mind the column formatting.

2017-05-05 07:57 UTC, dominikznidar commented on host_dflt.go
> -// +build ubuntu debian
Does `dflt` stand for `default`? If so, lets just use `default`.

2017-05-05 07:57 UTC, dominikznidar commented on host_dflt_test.go
> -// +build ubuntu debian
Same `dflt` to `default` comment here.

2017-05-05 07:57 UTC, dominikznidar commented on host_rhel.go
> +// +build rhel centos debian
It's a bit confusing `debian` is inside `host_rhel` file. This looks like a common generator for "What was ... thinking here ..." comments in the future :)

2017-05-05 08:25 UTC, lobiCode commented on Makefile
> +RPM 	      := sles opensuse
Line `12` has been removed. We don't need it

2017-05-05 08:26 UTC, lobiCode commented on host_dflt.go
> -// +build ubuntu debian
`dflt` has been changed to `default`

2017-05-05 08:26 UTC, lobiCode commented on host_dflt_test.go
> -// +build ubuntu debian
`dflt` has been changed to `default`

2017-05-08 07:35 UTC, dominikznidar approved these changes

2017-05-08 07:35 UTC, dominikznidar commented on host_rhel.go
> +// +build rhel centos debian
Lets just leave it for now.

2017-05-08 07:50 UTC, merged